### ISSUE TITLE
Plugin failed to initialize 

### ISSUE THREAD

**Issue by khamseen** [austinvaness/SkyboxPlugin#4]
Getting an error with this plugin since the game update.

2023-09-01 14:44:55.9773 [INFO] (1) Downloading https://github.com/austinvaness/SkyboxPlugin/archive/83b1502eb9e64452470fc56d381b751b65584750.zip
2023-09-01 14:44:58.1927 [ERROR] (1) CS1503: Argument 1: cannot convert from 'System.IO.Stream' to 'string' in file:
SkyboxPlugin-83b1502eb9e64452470fc56d381b751b65584750/SkyboxPlugin/SkyboxList.cs (163,63)
2023-09-01 14:44:58.1927 [ERROR] (1) Failed to load austinvaness/SkyboxPlugin|Skybox Mod Loader because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName, Byte[]& symbols)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, String assemblyName, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)

**Comment by austinvaness** [comment]
This should be fixed in the latest version

**Comment by khamseen** [comment]
Awesome, thanks!
